FROM python:3.9-slim
WORKDIR /app

# Ensure we install from the specific folder context
COPY pathfinding-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app source
COPY pathfinding-service/app ./app

# Google Cloud Run injects $PORT (Default 8080)
ENV PORT=8080
EXPOSE 8080

CMD uvicorn app.main:app --host 0.0.0.0 --port ${PORT}
